-- MySQL Script generated by MySQL Workbench
-- Sun Jan 19 04:06:17 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `cedula` VARCHAR(10) NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `fechaNaciemiento` DATE NOT NULL,
  `edad` SMALLINT NULL,
  `correoElectronico` VARCHAR(50) NOT NULL,
  `contraseña` VARCHAR(50) NOT NULL,
  `estadoVerificacion` ENUM('Pendiente', 'Verificado', 'Rechazado') NOT NULL DEFAULT 'Pendiente',
  `fotografia` MEDIUMBLOB NULL,
  `fechaCreacion` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`cedula`),
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proyectos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Proyectos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Proyectos` (
  `idProyectos` INT NOT NULL AUTO_INCREMENT,
  `nombreProyecto` VARCHAR(150) NULL,
  `descripcionProyecto` TEXT NULL,
  `categoriaProyecto` ENUM('Social', 'Comunitario', 'Ambiental', 'Desarrollo Económico') NULL,
  `provinciaProyecto` VARCHAR(45) NULL,
  `cuidadProyecto` VARCHAR(45) NULL,
  `impactoSocial` VARCHAR(45) NULL,
  `montoSolicitado` DECIMAL(15,2) NULL,
  `inicioPlazoProyecto` DATE NULL,
  `finPlazoProyecto` DATE NULL,
  `videoPresentacionProyecto` LONGBLOB NULL,
  `tipoRetorno` ENUM('Recompensa', 'Donación', 'Inversión') NULL,
  `kpi_Especificos` JSON NULL,
  `frecuenciaActualizaciones` ENUM('Mensual', 'Bimestre', 'Trimestre', 'Cuatrimestre', 'Semestre') NULL,
  `aceptacionTC` ENUM('si', 'no') NULL,
  `fechaCreacionProyecto` DATETIME NULL,
  PRIMARY KEY (`idProyectos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Validacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Validacion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Validacion` (
  `idValidaciones` INT NOT NULL AUTO_INCREMENT,
  `nombreValidacion` VARCHAR(45) NULL,
  `estadoValidacion` ENUM('Pendiente', 'Aceptada', 'Denegada') NULL,
  `fechaValidacion` DATETIME NULL,
  `documentacionCompelmentaria` MEDIUMBLOB NULL,
  `cronogramaActividades` JSON NULL,
  `firmaElectronica` TINYBLOB NULL,
  `Proyectos_idProyectos` INT NOT NULL,
  PRIMARY KEY (`idValidaciones`, `Proyectos_idProyectos`),
  INDEX `fk_Validacion_Proyectos1_idx` (`Proyectos_idProyectos` ASC) VISIBLE,
  CONSTRAINT `fk_Validacion_Proyectos1`
    FOREIGN KEY (`Proyectos_idProyectos`)
    REFERENCES `mydb`.`Proyectos` (`idProyectos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Multimedia_Evidencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Multimedia_Evidencia` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Multimedia_Evidencia` (
  `idMultimedia_Evidencia` INT NOT NULL AUTO_INCREMENT,
  `tituloEvidencia` VARCHAR(45) NULL,
  `fechaEvidencia` DATETIME NULL,
  `contenidoEvidencia` MEDIUMBLOB NULL,
  `fechaSubida` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `Proyectos_idProyectos` INT NOT NULL,
  PRIMARY KEY (`idMultimedia_Evidencia`, `Proyectos_idProyectos`),
  INDEX `fk_Multimedia_Evidencia_Proyectos1_idx` (`Proyectos_idProyectos` ASC) VISIBLE,
  CONSTRAINT `fk_Multimedia_Evidencia_Proyectos1`
    FOREIGN KEY (`Proyectos_idProyectos`)
    REFERENCES `mydb`.`Proyectos` (`idProyectos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Prestamista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Prestamista` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Prestamista` (
  `Usuario_cedula` VARCHAR(10) NOT NULL,
  `nivelEstudio` VARCHAR(45) NOT NULL,
  `ocupacion` VARCHAR(100) NOT NULL,
  `ingresosMensuales` DECIMAL(12,2) NULL,
  `preferenciaInversion` ENUM('Donacion', 'Recompensa', 'Rendiemiento') NULL,
  `metodoPagoPreferido` VARCHAR(45) NULL,
  PRIMARY KEY (`Usuario_cedula`),
  INDEX `fk_Prestamista_Usuario1_idx` (`Usuario_cedula` ASC) VISIBLE,
  UNIQUE INDEX `Usuario_cedula_UNIQUE` (`Usuario_cedula` ASC) VISIBLE,
  CONSTRAINT `fk_Prestamista_Usuario1`
    FOREIGN KEY (`Usuario_cedula`)
    REFERENCES `mydb`.`Usuario` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inversiones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Inversiones` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Inversiones` (
  `idInversiones` INT NOT NULL AUTO_INCREMENT,
  `montoInversion` DECIMAL(12,2) NULL,
  `tipoRetorno` ENUM('Recompensa', 'Donación', 'Inversión') NULL,
  `metodoPago` ENUM('Transferencia Bancaria', 'Tarjeta de Crédito', 'Billetera Digital') NULL,
  `fechaTransaccion` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `confirmacion_TYC` TINYINT NULL,
  `Proyectos_idProyectos` INT NOT NULL,
  `Prestamista_Usuario_cedula` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idInversiones`, `Proyectos_idProyectos`, `Prestamista_Usuario_cedula`),
  INDEX `fk_Inversiones_Proyectos1_idx` (`Proyectos_idProyectos` ASC) VISIBLE,
  INDEX `fk_Inversiones_Prestamista1_idx` (`Prestamista_Usuario_cedula` ASC) VISIBLE,
  CONSTRAINT `fk_Inversiones_Proyectos1`
    FOREIGN KEY (`Proyectos_idProyectos`)
    REFERENCES `mydb`.`Proyectos` (`idProyectos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inversiones_Prestamista1`
    FOREIGN KEY (`Prestamista_Usuario_cedula`)
    REFERENCES `mydb`.`Prestamista` (`Usuario_cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Prestatario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Prestatario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Prestatario` (
  `Usuario_cedula` VARCHAR(10) NOT NULL,
  `tipoOrganizacion` ENUM('Persona Individual', 'Organización Comunitaria', 'Empresa') NULL,
  `descripcionPerfil` TEXT NULL,
  `experienciaProyecto` JSON NULL,
  PRIMARY KEY (`Usuario_cedula`),
  INDEX `fk_Prestatario_Usuario1_idx` (`Usuario_cedula` ASC) VISIBLE,
  UNIQUE INDEX `Usuario_cedula_UNIQUE` (`Usuario_cedula` ASC) VISIBLE,
  CONSTRAINT `fk_Prestatario_Usuario1`
    FOREIGN KEY (`Usuario_cedula`)
    REFERENCES `mydb`.`Usuario` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Rol` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Rol` (
  `idRol` INT NOT NULL,
  `nombreRol` VARCHAR(50) NULL,
  PRIMARY KEY (`idRol`),
  UNIQUE INDEX `idRol_UNIQUE` (`idRol` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Informacion_Contacto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Informacion_Contacto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Informacion_Contacto` (
  `Usuario_cedula` VARCHAR(10) NOT NULL,
  `idRegistro_Personal` INT NOT NULL,
  `telefono` VARCHAR(13) NOT NULL,
  `provincia` VARCHAR(40) NOT NULL,
  `cuidad` VARCHAR(40) NOT NULL,
  `callePrincipal` VARCHAR(60) NULL,
  `calleSecundaria` VARCHAR(60) NULL,
  `codigoPostal` VARCHAR(6) NULL,
  `nroCasa` VARCHAR(7) NULL,
  PRIMARY KEY (`Usuario_cedula`, `idRegistro_Personal`),
  UNIQUE INDEX `idRegistro_Personal_UNIQUE` (`idRegistro_Personal` ASC) VISIBLE,
  INDEX `fk_Informacion_Contacto_Usuario1_idx` (`Usuario_cedula` ASC) VISIBLE,
  UNIQUE INDEX `Usuario_cedula_UNIQUE` (`Usuario_cedula` ASC) VISIBLE,
  CONSTRAINT `fk_Informacion_Contacto_Usuario1`
    FOREIGN KEY (`Usuario_cedula`)
    REFERENCES `mydb`.`Usuario` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Soporte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Soporte` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Soporte` (
  `Usuario_cedula` VARCHAR(10) NOT NULL,
  `nivelAcceso` ENUM('Superadmin', 'Verificador', 'Gestor') NULL,
  `especialidad` VARCHAR(100) NULL,
  `turno` ENUM('Mañana', 'Tarde', 'Noche') NULL,
  `departamento` VARCHAR(45) NULL,
  `casosAtendidos` INT NULL,
  `estado` ENUM('Activo', 'Inactivo') NOT NULL DEFAULT 'Activo',
  `fechaCreacion` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Usuario_cedula`),
  INDEX `fk_Soporte_Usuario1_idx` (`Usuario_cedula` ASC) VISIBLE,
  UNIQUE INDEX `Usuario_cedula_UNIQUE` (`Usuario_cedula` ASC) VISIBLE,
  CONSTRAINT `fk_Soporte_Usuario1`
    FOREIGN KEY (`Usuario_cedula`)
    REFERENCES `mydb`.`Usuario` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rol_has_Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Rol_has_Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Rol_has_Usuario` (
  `Rol_idRol` INT NOT NULL,
  `Usuario_cedula` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Rol_idRol`, `Usuario_cedula`),
  INDEX `fk_Rol_has_Usuario_Usuario1_idx` (`Usuario_cedula` ASC) VISIBLE,
  INDEX `fk_Rol_has_Usuario_Rol1_idx` (`Rol_idRol` ASC) VISIBLE,
  CONSTRAINT `fk_Rol_has_Usuario_Rol1`
    FOREIGN KEY (`Rol_idRol`)
    REFERENCES `mydb`.`Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rol_has_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_cedula`)
    REFERENCES `mydb`.`Usuario` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Administrador` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Administrador` (
  `Usuario_cedula` VARCHAR(10) NOT NULL,
  `nivelAcceso` ENUM('Superadmin', 'Verificador', 'Gestor') NULL,
  `areaSupervision` VARCHAR(100) NULL,
  `estado` ENUM('Activo', 'Suspendido') NOT NULL DEFAULT 'Activo',
  PRIMARY KEY (`Usuario_cedula`),
  INDEX `fk_Administrador_Usuario1_idx` (`Usuario_cedula` ASC) VISIBLE,
  UNIQUE INDEX `Usuario_cedula_UNIQUE` (`Usuario_cedula` ASC) VISIBLE,
  CONSTRAINT `fk_Administrador_Usuario1`
    FOREIGN KEY (`Usuario_cedula`)
    REFERENCES `mydb`.`Usuario` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Prestatario_has_Proyectos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Prestatario_has_Proyectos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Prestatario_has_Proyectos` (
  `Prestatario_Usuario_cedula` VARCHAR(10) NOT NULL,
  `Proyectos_idProyectos` INT NOT NULL,
  PRIMARY KEY (`Prestatario_Usuario_cedula`, `Proyectos_idProyectos`),
  INDEX `fk_Prestatario_has_Proyectos_Proyectos1_idx` (`Proyectos_idProyectos` ASC) VISIBLE,
  INDEX `fk_Prestatario_has_Proyectos_Prestatario1_idx` (`Prestatario_Usuario_cedula` ASC) VISIBLE,
  CONSTRAINT `fk_Prestatario_has_Proyectos_Prestatario1`
    FOREIGN KEY (`Prestatario_Usuario_cedula`)
    REFERENCES `mydb`.`Prestatario` (`Usuario_cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prestatario_has_Proyectos_Proyectos1`
    FOREIGN KEY (`Proyectos_idProyectos`)
    REFERENCES `mydb`.`Proyectos` (`idProyectos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
